### ISSUE TITLE
painter node is misaligned

### ISSUE THREAD

**Issue by za-wa-n-go** [AlekPet/ComfyUI_Custom_Nodes_AlekPet#1]
<img width="613" alt="image" src="https://github.com/AlekPet/ComfyUI_Custom_Nodes_AlekPet/assets/118154415/40d78ae6-9851-451e-9cd3-11f28ef95e69">
The painter node appears shifted like this.I am using chrome. Is this a difference in environment?

**Comment by za-wa-n-go** [comment]
Same PoseNode
<img width="570" alt="image" src="https://github.com/AlekPet/ComfyUI_Custom_Nodes_AlekPet/assets/118154415/4cd5bc48-0c7f-4fcc-b5ef-03db6e16e48b">

**Comment by AlekPet** [comment]
Hi, I have fixed this issue, please update and check.

**Comment by za-wa-n-go** [comment]
Thankyou!
<img width="345" alt="image" src="https://github.com/AlekPet/ComfyUI_Custom_Nodes_AlekPet/assets/118154415/0b2e6144-0e98-4c36-95d2-61dec8270899">
