### ISSUE TITLE
module 'pkgutil' has no attribute 'ImpImporter'

### ISSUE THREAD

**Issue by rayfeng-cq** [AlekPet/ComfyUI_Custom_Nodes_AlekPet#100]
I installed your nodes and following shown. I've re-git cloned it, reinstalled the ArgosTranslateNode, but the error is still there.  I'm using the latest ComfyUI and the python version is 3.12.7. Can anybody bail my out?
Traceback (most recent call last):
  File "E:\AI\ComfyUI_windows_portable_flux\ComfyUI\nodes.py", line 2027, in load_custom_node
    module_spec.loader.exec_module(module)
  File "<frozen importlib._bootstrap_external>", line 995, in exec_module
  File "<frozen importlib._bootstrap>", line 488, in _call_with_frames_removed
  File "E:\AI\ComfyUI_windows_portable_flux\ComfyUI\custom_nodes\ComfyUI_Custom_Nodes_AlekPet\__init__.py", line 275, in <module>
    from .ArgosTranslateNode.argos_translate_node import (
  File "E:\AI\ComfyUI_windows_portable_flux\ComfyUI\custom_nodes\ComfyUI_Custom_Nodes_AlekPet\ArgosTranslateNode\argos_translate_node.py", line 5, in <module>
    import argostranslate.translate
  File "E:\AI\ComfyUI_windows_portable_flux\python_embeded\Lib\site-packages\argostranslate\translate.py", line 5, in <module>
    import ctranslate2
  File "E:\AI\ComfyUI_windows_portable_flux\python_embeded\Lib\site-packages\ctranslate2\__init__.py", line 8, in <module>
    import pkg_resources
  File "E:\AI\ComfyUI_windows_portable_flux\python_embeded\Lib\site-packages\pkg_resources\__init__.py", line 2191, in <module>
    register_finder(pkgutil.ImpImporter, find_on_path)
                    ^^^^^^^^^^^^^^^^^^^
AttributeError: module 'pkgutil' has no attribute 'ImpImporter'. Did you mean: 'zipimporter'?

Cannot import E:\AI\ComfyUI_windows_portable_flux\ComfyUI\custom_nodes\ComfyUI_Custom_Nodes_AlekPet module for custom nodes: module 'pkgutil' has no attribute 'ImpImporter'

**Comment by AlekPet** [comment]
Hi, Most of the information can be found on the internet https://stackoverflow.com/a/77364602/23512000, you have a newer version of Python installed and some packages have changed in it.

**Comment by rayfeng-cq** [comment]
Thanks a lot!

**Comment by songzeyu5835** [comment]
![image](https://github.com/user-attachments/assets/2ba1a511-f560-492b-9c47-6439d8d8b5fc)

**Comment by songzeyu5835** [comment]
Our problems are not the same  ？Excuse me, how should I solve this problem

**Comment by songzeyu5835** [comment]
Excuse me, how should I solve this problem.

**Comment by Vagex** [comment]
> Excuse me, how should I solve this problem.

same problem

**Comment by AlekPet** [comment]
> Excuse me, how should I solve this problem.

Try this https://stackoverflow.com/a/77364602/23512000

**Comment by songzeyu5835** [comment]
Thank you very much.
It solves a problem I've been having for a long time

**Comment by Sdreamtale** [comment]
> > 请问，我该怎么解决这个问题。
> 
> 只试试这个你的环境舒适！： https://stackoverflow.com/a/77364602/23512000
> 
> 在 python_embeded 执行 cmd（或其他）并运行
> 
> .\python -m ensurepip --upgrade
> 和其他命令...

I have almost no understanding of the technical description of the computer. I can hardly figure out how to operate the methods mentioned here or where to do it. Could there be a detailed explanation or step-by-step instructions? This problem has been bothering me for a long time.

**Comment by AlekPet** [comment]
Hi.
Nothing complicated, comfyui has an environment (this is an isolated space on python where modules are installed so as not to install them everywhere in the system), that's where you should execute the necessary commands. Usually in comfyui this is the `python_embeded` folder (python files are located here), you can go to it with the explorer and in the top line where the path is enter cmd, and a terminal will open with the location in this folder. Here you can execute commands with the current environment or just use python commands with the modules installed in it. As an example `./python.exe -m pip list' - here, we simply call `pip` to see what modules are installed (the list value), as I wrote above, here you could see if googletrans is installed. Here you can also remove and install modules and other commands.
