### ISSUE TITLE
There is a problem with the ability to move layers up and down on the artboard

### ISSUE THREAD

**Issue by planb788** [AlekPet/ComfyUI_Custom_Nodes_AlekPet#11]
The buttons on the selection interface for moving layers hardly take effect.
In addition, it is recommended that the author add the following two functions: 1. One is the undo function with a limited number of steps. Because artboards are prone to misuse, adding unwanted elements is especially evident, especially if you choose tools such as triangles and rectangles to quickly create graphics. 2. Add a canvas cropping feature. Because many users need to crop pictures, but most of the existing nodes do not have a very intuitive tool for cropping pictures, resulting in very low efficiency in cropping pictures

**Comment by AlekPet** [comment]
By default, the option is “Bring Up Always”, so that when selecting the object is always in the foreground, turn it off.  If I understood you correctly.  About other possibilities as soon as you get your hands on them :).

**Comment by planb788** [comment]
> By default, the option is “Bring Up Always”, so that when selecting the object is always in the foreground, turn it off. I'll think about other possibilities :).
Thanks.
