### ISSUE TITLE
Is it possible to set the resolution of the paibter node?

### ISSUE THREAD

**Issue by knowknow0** [AlekPet/ComfyUI_Custom_Nodes_AlekPet#14]
Is it possible to set the resolution of the paibter node?

**Comment by AlekPet** [comment]
This is not available yet, but with the addition of crop it will be possible.

**Comment by AlekPet** [comment]
Add set canvas size, closed issue

**Comment by Grenwalls** [comment]
I've never been able to set the canvas size. When I click the button "canvas size" nothing happens. 
How is it supposed to be used? Any special tricks to it?

**Comment by AlekPet** [comment]
> I've never been able to set the canvas size. When I click the button "canvas size" nothing happens. 
> How is it supposed to be used? Any special tricks to it?

Hi. A modal window should appear unless of course they changed comfyu again with the update ))

**Comment by Grenwalls** [comment]
> > I've never been able to set the canvas size. When I click the button "canvas size" nothing happens.
> > How is it supposed to be used? Any special tricks to it?
> 
> Hi. A modal window should appear unless of course they changed comfyui again with the update )) see: [#48 (comment)](https://github.com/AlekPet/ComfyUI_Custom_Nodes_AlekPet/issues/48#issuecomment-2076707507)

Ooooo, tried to do it in the browser now, and then I do get the popup. 
But when I'm using the comfyui desktop app nothing happens. I guess the browser popup doesnt work in the desktop app. :(

**Comment by AlekPet** [comment]
Hmm, I just don't have the desktop version. Maybe you can enable modal windows there.

**Comment by AlekPet** [comment]
Try update comfyui desktop:  https://github.com/Comfy-Org/desktop/issues/486
