### ISSUE TITLE
Is it possible to add the translate method of argos translate library?

### ISSUE THREAD

**Issue by i11cn** [AlekPet/ComfyUI_Custom_Nodes_AlekPet#15]
[Argos Translate](https://github.com/argosopentech/argos-translate) is a powerful translation library running on local.
Can add it as a method to avoid network request?

**Comment by AlekPet** [comment]
I think it’s possible, there doesn’t seem to be anything complicated there, you’ll have to take a look ;)

**Comment by i11cn** [comment]
> I think it’s possible, there doesn’t seem to be anything complicated there, you’ll have to take a look ;) I'll try to create a node when I have time...

Thank you very much. That's really good news.

**Comment by AlekPet** [comment]
I added two nodes with Argos translator, use it.
[Argos Translate Node](https://github.com/AlekPet/ComfyUI_Custom_Nodes_AlekPet/tree/master/ArgosTranslateNode)

**Comment by i11cn** [comment]
It's cool, thank you.
