### ISSUE TITLE
error

### ISSUE THREAD

**Issue by liulsg** [AlekPet/ComfyUI_Custom_Nodes_AlekPet#16]
![image](https://github.com/AlekPet/ComfyUI_Custom_Nodes_AlekPet/assets/97494068/dc4beba7-32bc-4682-a52b-1947dc92ddcf)

**Comment by AlekPet** [comment]
Hello. You couldn’t write in more detail about which browser, whether there are ad blockers and other embellishments. Other nodes may be installed. Try opening it in a private tab, without browser extensions, and see if there are any errors in the Chrome browser console(ctrl+shift+i). Thank you!

**Comment by liulsg** [comment]
> Hello. You couldn’t write in more detail about which browser, whether there are ad blockers and other embellishments. Other nodes may be installed. Try opening it in a private tab, without browser extensions, and see if there are any errors in the Chrome browser console(ctrl+shift+i). Thank you!

@AlekPet  OK,I didn't have any description. It was my mistake. 
Browser: Chrome 
 ComfyUI Revision: 1735 [5b37270d] | Released on '2023-11-25'
alekpet node： fc22fdb

I'll try a few more times and get back to you. Thank you for your reply.

**Comment by AlekPet** [comment]
Fixed the error, everything should work now, update and check.
