### ISSUE TITLE
Can the canvas operate and display according to the width and height of the loaded image size

### ISSUE THREAD

**Issue by RayLam2022** [AlekPet/ComfyUI_Custom_Nodes_AlekPet#17]
Now the width and height of the painter node are consistent, and the read image will be distorted

**Comment by LiJT** [comment]
Yeah I was waiting for someone to bring that up.... The ratio seems not changable atm. locked at 1:1

**Comment by AlekPet** [comment]
When adding a bg image, I added a window for agreeing to change the canvas size equal to the image. Until I actually made the canvas in accordance with the aspect ratio, I don’t really understand the work of the resize node. =) But the output image has the correct ratio, it is only in the window that it is not distorted if the height and width are not equal. Sorry for my English.

**Comment by lzhfdwu007** [comment]
我不太清楚当我在画布涂抹一个区域后点击生成依然是改变了整张画？

**Comment by AlekPet** [comment]
Now I have added that only when loading the backround does the canvas change. But I’m going to add the ability to change the canvas, I’m struggling with the proportions when drawing the canvas.

**Comment by AlekPet** [comment]
Thank you, I’ll take a look, and you can move the preview of the mask ;)

**Comment by AlekPet** [comment]
Add suppot change canvas size. There may be problems with the size of the node in height, but these are minor things.
