### ISSUE TITLE
What's the mistake, please?

### ISSUE THREAD

**Issue by wibur0620** [AlekPet/ComfyUI_Custom_Nodes_AlekPet#18]
https://github.com/AlekPet/ComfyUI_Custom_Nodes_AlekPet/assets/131615326/06e592f5-a4a9-4bc4-9691-ee3e7c3a2aa2

**Comment by AlekPet** [comment]
This question has already been asked [Error here](https://github.com/AlekPet/ComfyUI_Custom_Nodes_AlekPet/issues/16), but I did not receive additional information, I will conduct more tests.  Thanks, I'll look into it.

**Comment by AlekPet** [comment]
Fixed the error, everything should work now, update and check.

**Comment by wibur0620** [comment]
Yes, it's back to normal now. Thank you
