### ISSUE TITLE
Can other translation engines be supported?

### ISSUE THREAD

**Issue by amimi818** [AlekPet/ComfyUI_Custom_Nodes_AlekPet#2]
Google Translate doesn't work properly in our area, it would be perfect if other translation engines such as DeepL or baidu were supported.

**Comment by AlekPet** [comment]
Hello, DeepL and Baidu need api keys, but I don’t have them, otherwise deep_translator for python could be used.

**Comment by amimi818** [comment]
I got it, thanks. Anyway, your nodes are great.

**Comment by AlekPet** [comment]
Add deep_translator.
[Deep translator nodes](https://github.com/AlekPet/ComfyUI_Custom_Nodes_AlekPet/tree/master/TranslateNode#deeptranslatortextnode-and-deeptranslatorcliptextencodenode)
