### ISSUE TITLE
Simmetry Suggestion

### ISSUE THREAD

**Issue by NicolasCampailla** [AlekPet/ComfyUI_Custom_Nodes_AlekPet#20]
Hello! I would like to suggest adding a symmetry toggle/s, that if pressed will copy anything you draw on a different axis you select, similairly to Canvas Tab by Lers (https://github.com/Lerc/canvas_tab).

**Comment by AlekPet** [comment]
Thanks, I'll have to take a look, very interesting.

**Comment by AlekPet** [comment]
Add symmetry brush https://github.com/AlekPet/ComfyUI_Custom_Nodes_AlekPet/tree/master/PainterNode#symmetry-brush
