### ISSUE TITLE
How to not translate specified words？

### ISSUE THREAD

**Issue by QianquanChina** [AlekPet/ComfyUI_Custom_Nodes_AlekPet#21]
Q：The trigger word of the Lora model is  **_diandian_**, but the translation software will translate it into _**Point**_，Please tell me how to deal with this situation, thanks for the reply
![image](https://github.com/AlekPet/ComfyUI_Custom_Nodes_AlekPet/assets/52106808/cccda572-9cc9-425e-97a7-86bd2843a9bc)

**Comment by AlekPet** [comment]
The translator translates everything that is given to him as input, slightly changing the translation, because  your own dictionaries for translation and variations.  The only thing that comes to my mind is either WAS_Text_List_Concatenate (https://github.com/WASasquatch/was-node-suite-comfyui/blob/main/WAS_Node_Suite.py), combining lines into one text, or you need to create a node that, for example  the enclosed word, as an example, @@word@@ was replaced by another. Sorry for my english.

**Comment by AlekPet** [comment]
> Q：The trigger word of the Lora model is **_diandian_**, but the translation software will translate it into _**Point**_，Please tell me how to deal with this situation, thanks for the reply ![image](https://private-user-images.githubusercontent.com/52106808/288037316-cccda572-9cc9-425e-97a7-86bd2843a9bc.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTEiLCJleHAiOjE3MDE5NjkyMzUsIm5iZiI6MTcwMTk2ODkzNSwicGF0aCI6Ii81MjEwNjgwOC8yODgwMzczMTYtY2NjZGE1NzItOWNjOS00MjVlLTk3YTctODZiZDI4NDNhOWJjLnBuZz9YLUFtei1BbGdvcml0aG09QVdTNC1ITUFDLVNIQTI1NiZYLUFtei1DcmVkZW50aWFsPUFLSUFJV05KWUFYNENTVkVINTNBJTJGMjAyMzEyMDclMkZ1cy1lYXN0LTElMkZzMyUyRmF3czRfcmVxdWVzdCZYLUFtei1EYXRlPTIwMjMxMjA3VDE3MDg1NVomWC1BbXotRXhwaXJlcz0zMDAmWC1BbXotU2lnbmF0dXJlPWI2NTdjYzZjMzI5YmI5YTYzYjg4NGNmZGE2ZTVlOTEwNDI4MWYxMTlmMDg0NjMzNzNlNmE3YjA2OTJmZTNjN2EmWC1BbXotU2lnbmVkSGVhZGVycz1ob3N0JmFjdG9yX2lkPTAma2V5X2lkPTAmcmVwb19pZD0wIn0.wnLh4VMGox-jaoc92hMSxVLYOLtYoNeivnkJYISe4eE)
**Bonus** :)
Or, as an option, add a manual translation, or rather, make a button in the translate node so that it immediately translates and displays it in the field, and then add the necessary words for lora to the already translated text and then generate the image.

**Comment by AlekPet** [comment]
I am modify, translate node =). Add button "Manual translate" or "Translate" not select name chosen yet. After click translate text, and return in field prompt input, then edit and generate image (text not translated again, i'am add boolean filed). Realese is coming ...

**Comment by QianquanChina** [comment]
> I am modify, translate node =). Add button "Manual translate" or "Translate" not select name chosen yet. After click translate text, and return in field prompt input, then edit and generate image (text not translated again, i'am add boolean filed). Realese is coming ...

Thank you very much for your attention to this question and the efforts you have made. I am looking forward to the next version.

**Comment by AlekPet** [comment]
Updatet translate node, add Manual button.

**Comment by QianquanChina** [comment]
> Updated translate node, add Manual button.

I tried the new feature and it solved the problem very well. This work is amazing!!!

**Comment by AlekPet** [comment]
Problem solved, topic closed.
