### ISSUE TITLE
ArgosTranslate Init Very Slow

### ISSUE THREAD

**Issue by KarryCharon** [AlekPet/ComfyUI_Custom_Nodes_AlekPet#26]
On my pc which cost over 7 seconds. And may be caused by the requirements checkModule function.
Some advice:
1. Mark a record file to identify the requirements condition
2. Check the python site-package directory instead of check installed every time
3. Delay the check phase

**Comment by AlekPet** [comment]
Yes, there is a long loading time, I will try to fix it, because...  Arogos is not small in size modules.

**Comment by AlekPet** [comment]
rewrote the module installation code, now threads are used.
