### ISSUE TITLE
I can't load the prompts from the old nodes.

### ISSUE THREAD

**Issue by za-wa-n-go** [AlekPet/ComfyUI_Custom_Nodes_AlekPet#27]
I am having trouble accessing the prompts used in past workflows.
Is there a good way to resolve this? I would appreciate it if you could make it possible to read past prompts as well.
<img width="716" alt="image" src="https://github.com/AlekPet/ComfyUI_Custom_Nodes_AlekPet/assets/118154415/98f77caa-e318-4ecc-9ec7-8691a962e28f">

**Comment by AlekPet** [comment]
Hi! Alternatively, you can try, open the workflow in a text editor and find my node translate there and see how it differs from the new one and replace it in the right places.

**Comment by AlekPet** [comment]
Or comments three line to the file in the custom_nodes/translate_node/js/googletranslate.js

1. toggle
2. toggle false
3 splice

 
https://github.com/AlekPet/ComfyUI_Custom_Nodes_AlekPet/blob/master/TranslateNode%2Fjs%2Fgoogle_translate_node.js#L87

**Comment by za-wa-n-go** [comment]
<img width="528" alt="image" src="https://github.com/AlekPet/ComfyUI_Custom_Nodes_AlekPet/assets/118154415/6e32ea5d-ca56-4f47-abd4-4851257618f1">

humm...

**Comment by za-wa-n-go** [comment]
It would probably be beneficial if the Manual feature is implemented not as an upgrade to existing nodes, but rather as a new node addition. This way, we could continue to use our past assets as they are. If it's still possible to do so, that would be great.

**Comment by AlekPet** [comment]
I understand what the problem is, I will fix it soon.  Here's a temporary solution.
```
node.widgets[2].type = "toggle";
node.widgets[2].value = false;
 
 const toggle = node.widgets.splice(2,1)[0];
 node.widgets.splice(3,0,toggle);
```

**Comment by AlekPet** [comment]
> It would probably be beneficial if the Manual feature is implemented not as an upgrade to existing nodes, but rather as a new node addition. This way, we could continue to use our past assets as they are. If it's still possible to do so, that would be great.

Everything is possible! :)

**Comment by za-wa-n-go** [comment]
great!!
