### ISSUE TITLE
PoseNode cannot switch image

### ISSUE THREAD

**Issue by lldacing** [AlekPet/ComfyUI_Custom_Nodes_AlekPet#28]
I found follow two errors, but it still don't work after fixed, because code "const callb = this.node.callback" is undefined (figure 1).
![image](https://github.com/AlekPet/ComfyUI_Custom_Nodes_AlekPet/assets/43737696/f8cd0bb1-a83c-44e0-93fa-685030b7dafa)
![image](https://github.com/AlekPet/ComfyUI_Custom_Nodes_AlekPet/assets/43737696/d694e791-2e9f-4ec3-a0fd-a958e080423d)

**Comment by AlekPet** [comment]
Hi. Yes, I saw errors, but I didn’t understand why change the images, this is an interactive node, there is no need to load an image here, I can add the ability to load a background.

**Comment by lldacing** [comment]
> Hi. Yes, I saw errors, but I didn’t understand why change the images, this is an interactive node, there is no need to load an image here, I can add the ability to load a background.你好。是的，我看到了错误，但我不明白为什么要更改图像，这是一个交互式节点，这里不需要加载图像，我可以添加加载背景的功能。

I have an openpose image generated based on the openpose preprocessor. How should I load it into this node?

**Comment by AlekPet** [comment]
Hello. Is it just an image? Or is it a json file? If this is an image, then you can use the Load Image node, and then used controlnet, but if this is a json file, then this cannot be done yet. I have not implemented this function in this node, although it is possible.
