### ISSUE TITLE
painter node does not show the canvas

### ISSUE THREAD

**Issue by hheavenknowss** [AlekPet/ComfyUI_Custom_Nodes_AlekPet#30]
hi there, thanks to your wonderful work!
I have an issue when I try to use painter node, when I added a painter Node, it looks like this:
![image](https://github.com/AlekPet/ComfyUI_Custom_Nodes_AlekPet/assets/35052711/ff64a6ed-cea3-4fa9-a7ff-a74cdf53e54f)
but I think it should be like this:
![image](https://github.com/AlekPet/ComfyUI_Custom_Nodes_AlekPet/assets/35052711/6fc1386c-44e3-47be-93d2-d91afe8de4c4)
any idea what's going on ?

**Comment by AlekPet** [comment]
Hello! Are there any errors in the console in the browser (Chrome F12) or errors in the window itself ComfyUI? Need more information, check if there is a folder in the ComfyUI/web/extensions/AlekPet_Nodes inside this folder file painter_node.js, and in folder ComfyUI/web/lib file fabic.js. I just looked at myself and everything works. What revision ComfyUI.

**Comment by hheavenknowss** [comment]
> Hello! Are there any errors in the console in the browser (Chrome F12) or errors in the window itself ComfyUI? Need more information, check if there is a folder in the ComfyUI/web/extensions/AlekPet_Nodes inside this folder file painter_node.js, and in folder ComfyUI/web/lib file fabic.js. I just looked at myself and everything works. What revision ComfyUI.

I checked my project folder, everyFile looks fine, and I tried on my local MAC, everything works fine, but on the linux, things getting to strange. ComfyUI revision is the latest vision.

I think it may not be your code, just because my enviroment on linux.

thx~!

**Comment by LuckyFan** [comment]
It happened to me as well in certain workflow, but works in other workflow, I am not sure why
<img width="532" alt="image" src="https://github.com/AlekPet/ComfyUI_Custom_Nodes_AlekPet/assets/4580969/ae5fce7c-3dac-4a56-a374-4b5ad4c22055">

**Comment by AaronPanXiaoFeng** [comment]
@hheavenknowss I encountered the same problem: painter node does not show the canvas. It seems that painter node can't work on linux @AlekPet

**Comment by AlekPet** [comment]
It will be necessary to raise the virtual machine to test what is wrong there linux with PainterNode. ^_^

**Comment by AaronPanXiaoFeng** [comment]
@AlekPet 
![painter_node_err](https://github.com/AlekPet/ComfyUI_Custom_Nodes_AlekPet/assets/52602270/54dc7c92-525d-4a82-ae88-3f263f43106b)
It seems painter_node.js is not loaded.

**Comment by AlekPet** [comment]
Judging by the errors, the problem is not only in my node (Davemane42), it is more likely related to the browser or comfyui, which cannot dynamically load script modules.  Are you running something other than LAN (dsw-gateway.alibaba-inc....)?  You can create a topic in the comfyui repository.

**Comment by AlekPet** [comment]
I installed Ubuntu on a virtual machine, everything works, look for errors in the browser console or in the comfort window.
Screenshot two browser, chrome and firefox:
![comfyui ubuntu](https://github.com/AlekPet/ComfyUI_Custom_Nodes_AlekPet/assets/25489996/14f54b95-ce8f-4bcb-b692-462ba82a768f)

**Comment by oqupspipe** [comment]
The problem has been solved,

**Comment by AaronPanXiaoFeng** [comment]
> I installed Ubuntu on a virtual machine, everything works, look for errors in the browser console or in the comfort window. Screenshot two browser, chrome and firefox: ![comfyui ubuntu](https://private-user-images.githubusercontent.com/25489996/298296032-14f54b95-ce8f-4bcb-b692-462ba82a768f.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MDU5ODA0MTUsIm5iZiI6MTcwNTk4MDExNSwicGF0aCI6Ii8yNTQ4OTk5Ni8yOTgyOTYwMzItMTRmNTRiOTUtY2U4Zi00YmNiLWI2OTItNDYyYmE4MmE3NjhmLnBuZz9YLUFtei1BbGdvcml0aG09QVdTNC1ITUFDLVNIQTI1NiZYLUFtei1DcmVkZW50aWFsPUFLSUFWQ09EWUxTQTUzUFFLNFpBJTJGMjAyNDAxMjMlMkZ1cy1lYXN0LTElMkZzMyUyRmF3czRfcmVxdWVzdCZYLUFtei1EYXRlPTIwMjQwMTIzVDAzMjE1NVomWC1BbXotRXhwaXJlcz0zMDAmWC1BbXotU2lnbmF0dXJlPWMxNWMzNGI2MmRmMmJhMWZiYzAxYjdlNGUwMGM1Y2ZhMmNhMGQzZDAwNDM0Y2Q2MGM3NDBjNzFmYjk2MzhiYTEmWC1BbXotU2lnbmVkSGVhZGVycz1ob3N0JmFjdG9yX2lkPTAma2V5X2lkPTAmcmVwb19pZD0wIn0.A5lLMQVCtVxhWmkx4I-C12FzZbJj06bmnxmWZ5Kvkzs)

The problem may be caused by the fact that I run comfy on a remote server while open the comfy webUI on my local PC.

**Comment by AlekPet** [comment]
> > I installed Ubuntu on a virtual machine, everything works, look for errors in the browser console or in the comfort window. Screenshot two browser, chrome and firefox: ![comfyui ubuntu](https://private-user-images.githubusercontent.com/25489996/298296032-14f54b95-ce8f-4bcb-b692-462ba82a768f.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MDU5ODA0MTUsIm5iZiI6MTcwNTk4MDExNSwicGF0aCI6Ii8yNTQ4OTk5Ni8yOTgyOTYwMzItMTRmNTRiOTUtY2U4Zi00YmNiLWI2OTItNDYyYmE4MmE3NjhmLnBuZz9YLUFtei1BbGdvcml0aG09QVdTNC1ITUFDLVNIQTI1NiZYLUFtei1DcmVkZW50aWFsPUFLSUFWQ09EWUxTQTUzUFFLNFpBJTJGMjAyNDAxMjMlMkZ1cy1lYXN0LTElMkZzMyUyRmF3czRfcmVxdWVzdCZYLUFtei1EYXRlPTIwMjQwMTIzVDAzMjE1NVomWC1BbXotRXhwaXJlcz0zMDAmWC1BbXotU2lnbmF0dXJlPWMxNWMzNGI2MmRmMmJhMWZiYzAxYjdlNGUwMGM1Y2ZhMmNhMGQzZDAwNDM0Y2Q2MGM3NDBjNzFmYjk2MzhiYTEmWC1BbXotU2lnbmVkSGVhZGVycz1ob3N0JmFjdG9yX2lkPTAma2V5X2lkPTAmcmVwb19pZD0wIn0.A5lLMQVCtVxhWmkx4I-C12FzZbJj06bmnxmWZ5Kvkzs)
> 
> The problem may be caused by the fact that I run comfy on a remote server while open the comfy webUI on my local PC.

And it blocks third-party modules :)

**Comment by aousxx** [comment]
whitelisting for adblock browser extension fixed it for me, even thought it said 0 was blocked ...

**Comment by AlekPet** [comment]
The issue has been resolved, thread closed.

**Comment by Spinaster** [comment]
Is there a way to load a generated image as canvas? I know is possible to load an external image but not one created in the same workflow. Thank you!

**Comment by AlekPet** [comment]
> Is there a way to load a generated image as canvas? I know is possible to load an external image but not one created in the same workflow. Thank you!

https://github.com/AlekPet/ComfyUI_Custom_Nodes_AlekPet/issues/24

Hello, if you mean is it possible to input a generated image from another node, then this is not possible yet.
