### ISSUE TITLE
Feature: Backgound image in Pose Node [with patch]

### ISSUE THREAD

**Issue by techtruth** [AlekPet/ComfyUI_Custom_Nodes_AlekPet#35]
I was missing the ability to set a background image, and then move the pose markers to match it. This is very handy for setting manual poses for images.

I notices the pose node plus plugin has this feature, and got this patch that is only a little different than their approach.

This uses fabric's native backgroundimage method, but removes the image before it it written to comfyUI temp folder and so is not used as actual input. Only the open pose markings with the black background are used as input.

[backgroundimage.patch.txt](https://github.com/AlekPet/ComfyUI_Custom_Nodes_AlekPet/files/14161305/backgroundimage.patch.txt)

There does seem to be a bug remaining around the undo key, but I think that is not related to this patch.

Thanks for these great additional nodes. I'd like to use it with faces and hands one day. ;)

**Comment by AlekPet** [comment]
Hi, ok it will be done when time permits. When generating, the background will simply be removed. I finished a symmetrical brush today https://github.com/AlekPet/ComfyUI_Custom_Nodes_AlekPet/tree/master/PainterNode#symmetry-brush

**Comment by AlekPet** [comment]
Make pull request and i am see ;)

**Comment by AlekPet** [comment]
> I was missing the ability to set a background image, and then move the pose markers to match it. This is very handy for setting manual poses for images.
> 
> I notices the pose node plus plugin has this feature, and got this patch that is only a little different than their approach.
> 
> This uses fabric's native backgroundimage method, but removes the image before it it written to comfyUI temp folder and so is not used as actual input. Only the open pose markings with the black background are used as input.
> 
> [backgroundimage.patch.txt](https://github.com/AlekPet/ComfyUI_Custom_Nodes_AlekPet/files/14161305/backgroundimage.patch.txt)
> 
> There does seem to be a bug remaining around the undo key, but I think that is not related to this patch.
> 
> Thanks for these great additional nodes. I'd like to use it with faces and hands one day. ;)

Added thanks for the help! Closed the topic.
