### ISSUE TITLE
After reopening A workflow DeepTranslatorTextNode does not remember the previously selected language

### ISSUE THREAD

**Issue by ShmuelRonen** [AlekPet/ComfyUI_Custom_Nodes_AlekPet#38]
I have a workflow with several DeepTranslatorTextNodes, every time I reopen it I have to update the language selection in each of them, because the node does not remember the previously selected language.

It's quite frustrating and I would ask if you could fix this problem.

**Comment by AlekPet** [comment]
> I have a workflow with several DeepTranslatorTextNodes, every time I reopen it I have to update the language selection in each of them, because the node does not remember the previously selected language.
> 
> It's quite frustrating and I would ask if you could fix this problem.

Hello, I'll see what can be done, this is not an easy matter, because... there are many services to choose from.

**Comment by ShmuelRonen** [comment]
It can be solved by a json file where the last state is saved. And only when changing language, it registers the new state.

**Comment by AlekPet** [comment]
> It can be solved by a json file where the last state is saved. And only when changing language, it registers the new state.

Perhaps it can be done this way, it’s just that there are different instances of DeepTranslator in different workflow assemblies and they need to be identified somehow, I’m more inclined to serialize the data, but I’m not sure yet.

**Comment by AlekPet** [comment]
> I have a workflow with several DeepTranslatorTextNodes, every time I reopen it I have to update the language selection in each of them, because the node does not remember the previously selected language.
> 
> It's quite frustrating and I would ask if you could fix this problem.

Fixed it, now it should save the selected languages, test it.

**Comment by ShmuelRonen** [comment]
Thanks!!! make update now

**Comment by ShmuelRonen** [comment]
It's works perfect!!!
