### ISSUE TITLE
How do you draw a mask with the painter node?

### ISSUE THREAD

**Issue by RedDeltas** [AlekPet/ComfyUI_Custom_Nodes_AlekPet#40]
Hi, I love the painter node - it is the best of it's kind that I've found.

I notice it has a mask output but I've not worked out how to make it output a mask yet.
How do I achieve this?

**Comment by florestefano1975** [comment]
![Screenshot 2024-03-10 194436.png](https://github.com/AlekPet/ComfyUI_Custom_Nodes_AlekPet/assets/153757302/f58a6236-41e9-4528-b526-d28eb3eb4017)

**Comment by AlekPet** [comment]
> ![Screenshot 2024-03-10 194436.png](https://private-user-images.githubusercontent.com/153757302/311545285-f58a6236-41e9-4528-b526-d28eb3eb4017.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MTAxNDQ1NTEsIm5iZiI6MTcxMDE0NDI1MSwicGF0aCI6Ii8xNTM3NTczMDIvMzExNTQ1Mjg1LWY1OGE2MjM2LTQxZTktNDUyOC1iNTI2LWQyOGViM2ViNDAxNy5wbmc_WC1BbXotQWxnb3JpdGhtPUFXUzQtSE1BQy1TSEEyNTYmWC1BbXotQ3JlZGVudGlhbD1BS0lBVkNPRFlMU0E1M1BRSzRaQSUyRjIwMjQwMzExJTJGdXMtZWFzdC0xJTJGczMlMkZhd3M0X3JlcXVlc3QmWC1BbXotRGF0ZT0yMDI0MDMxMVQwODA0MTFaJlgtQW16LUV4cGlyZXM9MzAwJlgtQW16LVNpZ25hdHVyZT1kMGI2ODk5OGZiN2UzZWE5ZjM5YTM3NGJjZGFjZGMzY2JlNzhkYTI4OWQ0MzM2MTRkYTNiYmQzNGJjYjExNTU5JlgtQW16LVNpZ25lZEhlYWRlcnM9aG9zdCZhY3Rvcl9pZD0wJmtleV9pZD0wJnJlcG9faWQ9MCJ9.1jnRBrUnWwTzjwNSIfJrNzQXzzvm4yL6U42FgrqRYNY)

Right mouse button on the gray area where Open Mask Editor

**Comment by AlekPet** [comment]
> > Hi, Right mouse button on the gray area where Open Mask Editor
> 
> Hi, actually I have no problems using the node, I proposed a solution to whoever opened the request.

Sorry)) Didn't notice

**Comment by RedDeltas** [comment]
Thank you, using the Mask Editor worked great - I just hadn't realised that you needed to right-click the area around the canvas instead 😁
