### ISSUE TITLE
AttributeError: 'ComfyUIManagerLogger' object has no attribute 'isatty'

### ISSUE THREAD

**Issue by dtyty1895** [AlekPet/ComfyUI_Custom_Nodes_AlekPet#43]
![image](https://github.com/AlekPet/ComfyUI_Custom_Nodes_AlekPet/assets/83059760/fe1de813-552b-44af-b1d4-e73650d01e51)

**Comment by AlekPet** [comment]
Hey, I'll see when I have time.
https://github.com/AlekPet/ComfyUI_Custom_Nodes_AlekPet/issues/41

**Comment by cxyfreedom** [comment]
same problem

**Comment by AlekPet** [comment]
I looked, if I remove the comfyui manager, then everything works.  Must watch.

**Comment by cxyfreedom** [comment]
> I looked, if I remove the comfyui manager, then everything works. Must watch.

I don't this error detail. My solution is below. vim `site-packages/stanza/utils/get_tqdm.py`.

**Comment by AlekPet** [comment]
You can correct the code in the modules so that the manager does not demolish it.

Fix module tqdm:
../python_embeded/Lib/site-packages/stanza/utils/get_tqdm.py

Line 34:
```python
    if sys.stderr is not None and sys.stderr.isatty():
```

Change to:
```
    if sys.stderr is not None and hasattr(sys.stderr, "isatty") and sys.stderr.isatty():
```

**Comment by mufenglyf** [comment]
![image](https://github.com/AlekPet/ComfyUI_Custom_Nodes_AlekPet/assets/141204761/1daf0387-7988-4fe9-8a19-3542a9529d07)
This is the manager's prompt

**Comment by VedanthB** [comment]
sae error, how can i fis this ?

**Comment by dtyty1895** [comment]
@cxyfreedom @AlekPet Thank u ! it can work !

**Comment by dtyty1895** [comment]
@VedanthB Just follow the above and it will work !

**Comment by VedanthB** [comment]
@dtyty1895 i am running comfy UI on a colab notebook, where can i find `/site-packages/stanza/utils/get_tqdm.py` ?

**Comment by AlekPet** [comment]
> @dtyty1895 i am running comfy UI on a colab notebook, where can i find `/site-packages/stanza/utils/get_tqdm.py` ?
> 
> 
> 

If you don't need ArgosTranslate, delete the folder in custom_nodes

**Comment by VedanthB** [comment]
@AlekPet I need the translate node

**Comment by AlekPet** [comment]
> @AlekPet I need the translate node
> 

Alternatively, remove (temporarily) the manager or remove it from the nodes, or wait for the stanza update or use another translator.

**Comment by dtyty1895** [comment]
@VedanthB I help you find the stanza path in Colab, you need to modify the content described above.
![image](https://github.com/AlekPet/ComfyUI_Custom_Nodes_AlekPet/assets/83059760/947731a1-2040-43ba-b8ca-b91fa7c12e9d)

**Comment by hmongdev** [comment]
> You can correct the code in the modules so that the manager does not demolish it.
> 
> Fix module tqdm: ../python_embeded/Lib/site-packages/stanza/utils/get_tqdm.py
> 
> Line 34:
> 
> ```python
>     if sys.stderr is not None and sys.stderr.isatty():
> ```
> 
> Change to:
> 
> ```python
>     if sys.stderr is not None and hasattr(sys.stderr, "isatty") and sys.stderr.isatty():
> ```

This works! Thank you.

1. Find the `get_tqdm.py` file:

![Screenshot 2024-03-15 213540](https://github.com/AlekPet/ComfyUI_Custom_Nodes_AlekPet/assets/94493230/9e509dde-8151-46de-add3-00720349f743)

2. Change line 34
`if sys.stderr is not None and hasattr(sys.stderr, "isatty") and sys.stderr.isatty():`

![Screenshot 2024-03-15 213733](https://github.com/AlekPet/ComfyUI_Custom_Nodes_AlekPet/assets/94493230/c1737fa9-9b2b-4b9d-a4bf-36f83ff0141e)

3. Restart ComfyUI

**Comment by kiklauss** [comment]
> > You can correct the code in the modules so that the manager does not demolish it.
> > Fix module tqdm: ../python_embeded/Lib/site-packages/stanza/utils/get_tqdm.py
> > Line 34:
> > ```python
> >     if sys.stderr is not None and sys.stderr.isatty():
> > ```
> > 
> > 
> >     
> >       
> >     
> > 
> >       
> >     
> > 
> >     
> >   
> > Change to:
> > ```python
> >     if sys.stderr is not None and hasattr(sys.stderr, "isatty") and sys.stderr.isatty():
> > ```
> 
> This works! Thank you.
> 
> 1. Find the `get_tqdm.py` file:
> 
> ![Screenshot 2024-03-15 213540](https://private-user-images.githubusercontent.com/94493230/313367252-9e509dde-8151-46de-add3-00720349f743.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MTA1Nzk5OTQsIm5iZiI6MTcxMDU3OTY5NCwicGF0aCI6Ii85NDQ5MzIzMC8zMTMzNjcyNTItOWU1MDlkZGUtODE1MS00NmRlLWFkZDMtMDA3MjAzNDlmNzQzLnBuZz9YLUFtei1BbGdvcml0aG09QVdTNC1ITUFDLVNIQTI1NiZYLUFtei1DcmVkZW50aWFsPUFLSUFWQ09EWUxTQTUzUFFLNFpBJTJGMjAyNDAzMTYlMkZ1cy1lYXN0LTElMkZzMyUyRmF3czRfcmVxdWVzdCZYLUFtei1EYXRlPTIwMjQwMzE2VDA5MDEzNFomWC1BbXotRXhwaXJlcz0zMDAmWC1BbXotU2lnbmF0dXJlPTM1Y2RkN2VjNTI0YTcyNDc3MGNiNGY3YzRkMzE0MWE1MjZjMzBlMWM5MDY5MzMxNjk1OTY1YjdhMTllMTI2MzEmWC1BbXotU2lnbmVkSGVhZGVycz1ob3N0JmFjdG9yX2lkPTAma2V5X2lkPTAmcmVwb19pZD0wIn0.L3GPzCj4dRQ6au4StZklJTS08t1BVPylH7xfTfnavK0)
> 
> 2. Change line 34
>    `if sys.stderr is not None and hasattr(sys.stderr, "isatty") and sys.stderr.isatty():`
> 
> ![Screenshot 2024-03-15 213733](https://private-user-images.githubusercontent.com/94493230/313367791-c1737fa9-9b2b-4b9d-a4bf-36f83ff0141e.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MTA1Nzk5OTQsIm5iZiI6MTcxMDU3OTY5NCwicGF0aCI6Ii85NDQ5MzIzMC8zMTMzNjc3OTEtYzE3MzdmYTktOWIyYi00YjlkLWE0YmYtMzZmODNmZjAxNDFlLnBuZz9YLUFtei1BbGdvcml0aG09QVdTNC1ITUFDLVNIQTI1NiZYLUFtei1DcmVkZW50aWFsPUFLSUFWQ09EWUxTQTUzUFFLNFpBJTJGMjAyNDAzMTYlMkZ1cy1lYXN0LTElMkZzMyUyRmF3czRfcmVxdWVzdCZYLUFtei1EYXRlPTIwMjQwMzE2VDA5MDEzNFomWC1BbXotRXhwaXJlcz0zMDAmWC1BbXotU2lnbmF0dXJlPTI2ODY0ZTlmMTZmYWI2Mjg5NWVjOGM5MTBmYjM5MmE5Njg3MWY1NjBlOTUyNGI3OWY1MzY2NWNhMDcwNjAwNTEmWC1BbXotU2lnbmVkSGVhZGVycz1ob3N0JmFjdG9yX2lkPTAma2V5X2lkPTAmcmVwb19pZD0wIn0.W0ALMB8HSwfcyYTcrqiSJgFDnq-ys0jdc2JK55cfyK4)
> 
> 3. Save File
> 4. Restart ComfyUI
> 
> Enjoy 🥳

This works! Thank you.

**Comment by alexbofa** [comment]
Hello
You need to go to `Manager` → `Install PIP packages` → put `stanza==1.2.3` and **restart**

**Comment by jacochen** [comment]
> Hello You need to go to `Manager` → `Install PIP packages` → put `stanza==1.2.3` and **restart**

This works! Thank you.

**Comment by valleyss** [comment]
i have same pr

> Hello You need to go to `Manager` → `Install PIP packages` → put `stanza==1.2.3` and **restart**

i did what you said,then the another problem occured ： “This action is not allowed with this security level configuration.” 
i use this docker https://hub.docker.com/r/yanwk/comfyui-boot
