### ISSUE TITLE
Does this plugin support Ubuntu?

### ISSUE THREAD

**Issue by jiangdi0924** [AlekPet/ComfyUI_Custom_Nodes_AlekPet#49]
Does this plugin support Ubuntu? 

installed  and comfyUI not worked

**Comment by AlekPet** [comment]
> Does this plugin support Ubuntu? 
> 
> installed  and comfyUI not worked

Hello, yes https://github.com/AlekPet/ComfyUI_Custom_Nodes_AlekPet/issues/30#issuecomment-1902173733

**Comment by jiangdi0924** [comment]
It has been verified.
