### ISSUE TITLE
screen freezes.

### ISSUE THREAD

**Issue by za-wa-n-go** [AlekPet/ComfyUI_Custom_Nodes_AlekPet#5]
After updating ComfyUI, it seems that the screen freezes and requires reloading when starting generation using the PreviewText node.
If the PreviewText node is not used, the screen never freezes.
I am using ShowText|pyssss instead and hope to be able to use PreviewText as it is cleaner to look at.

**Comment by fr0nky0ng** [comment]
the same issue

**Comment by AlekPet** [comment]
Hello everyone, I replaced the function in which the field is updated, now it should not slow down. Thank you.

**Comment by za-wa-n-go** [comment]
Thanks for the response!
It no longer freezes, but the text doesn't seem to be output.
Is it because I am using text concatenate? But it used to output it before.

**Comment by za-wa-n-go** [comment]
<img width="668" alt="image" src="https://github.com/AlekPet/ComfyUI_Custom_Nodes_AlekPet/assets/118154415/538970a1-aa64-4381-8181-6b034b83f362">

**Comment by AlekPet** [comment]
Apparently, at startup, it does not always update the view of the node, I tried to return the previous code with redrawing the node, limiting this redrawing, only if it has changed, I don’t know if there will be friezes now

**Comment by AlekPet** [comment]
Check current script in repository or this:
```import { app } from "/scripts/app.js";
import { ComfyWidgets } from "/scripts/widgets.js";

app.registerExtension({
  name: "Comfy.ExtrasNode",
  async beforeRegisterNodeDef(nodeType, nodeData, app) {
    if (nodeData.name === "PreviewTextNode") {
      // Node Created
      const onNodeCreated = nodeType.prototype.onNodeCreated;
      nodeType.prototype.onNodeCreated = function () {
        const r = onNodeCreated
          ? onNodeCreated.apply(this, arguments)
          : undefined;

        let PreviewTextNode = app.graph._nodes.filter(
            (wi) => wi.type == "PreviewTextNode"
          ),
          nodeName = `PreviewTextNode_${PreviewTextNode.length}`;

        console.log(`Create PreviewTextNode: ${nodeName}`);

        ComfyWidgets.STRING(
          this,
          nodeName,
          [
            "STRING",
            {
              default: "",
              placeholder: "Text message output...",
              multiline: true,
            },
          ],
          app
        );
        return r;
      };

      // Node Executed
      const onNodeExecuted = nodeType.prototype.onExecuted;
      nodeType.prototype.onExecuted = function () {
        onNodeExecuted?.apply(this, arguments);

        const output = app.nodeOutputs[this.id + ""];
        if (output && output.string) {
          this.widgets[0].inputEl.value = output.string[0];
          this.widgets[0].inputEl.readOnly = true;
          app.graph.setDirtyCanvas(true, true);
        }
      };
    }
  },
});
```
add line  **app.graph.setDirtyCanvas(true, true);**

**Comment by za-wa-n-go** [comment]
It seems to freeze up again.

**Comment by AlekPet** [comment]
I just can’t reproduce the hang to check, I didn’t notice it myself, maybe it depends on the performance of the iron. The code above, which is executed at startup, should not slow down, since it is executed once (but apparently does not always redraw the node), the code that is now in the repository is executed when it is redrawn, so it freezes, although it added an update only if the data is different. It should correctly execute in the onExecuted function, not in onDrawForeground or onDrawBackground.

**Comment by za-wa-n-go** [comment]
Hmmm... Is it a compatibility issue?
I'm going to use ShowText|pyssss since it's easier to use and it's more convenient to use!
