### ISSUE TITLE
[SSL: CERTIFICATE_VERIFY_FAILED]

### ISSUE THREAD

**Issue by za-wa-n-go** [AlekPet/ComfyUI_Custom_Nodes_AlekPet#53]
httpx.ConnectError: [SSL: CERTIFICATE_VERIFY_FAILED] certificate verify failed: self signed certificate in certificate chain (_ssl.c:1007)

When using the GoogleTranslate node, it seems that an error occurs at the SSL certification step.

There appears to be a way to handle this, but I would like to avoid editing the code within the venv.
Is there a way to handle this on the node side?

**Comment by AlekPet** [comment]
Hello, there was already such an error somewhere, try removing 
```py
.\python_embed\Python.exe -m pip uninstall googletrans-py
```
and installing 
```py
.\python_embed\Python.exe -m pip uninstall googletrans==3.1.0a0
```

**Comment by za-wa-n-go** [comment]
It seems like it's no good. I think it's due to the security settings of the network in this environment. If you set `verify=false` in a certain part of `client.py` in googletrans's site-packages in the venv, it works, but it's a hassle to do it every time you reinstall, so I'm looking for a better way.

**Comment by AlekPet** [comment]
As an option, you can make a patch that would patch this client.py file when you start comfyui (in the bat, sh file, before starting comfyui) if the value is True, using the example of my patch for Fooocus.

**Comment by za-wa-n-go** [comment]
Thankyou.
Can this be prevented by installing this?
https://github.com/AlekPet/Fooocus_Extensions_AlekPet

**Comment by AlekPet** [comment]
> Thankyou.
> Can this be prevented by installing this?
> https://github.com/AlekPet/Fooocus_Extensions_AlekPet

No, I wrote by analogy, you can make a patch that will patch the file at startup if it does not correspond to the required code.
