### ISSUE TITLE
Empty Painter node after clean install

### ISSUE THREAD

**Issue by rezponze** [AlekPet/ComfyUI_Custom_Nodes_AlekPet#55]
Hi! I just installed the nodes after updating Comfy and Manager and I get and empty Painter node. Pose node loads ok, so it seems is just an Issue with Painter Node. 

I get no errors in console when loading the node, just an empty node. Any hint :) thanks!  

![Screenshot 2024-06-01 at 14-29-47 ComfyUI](https://github.com/AlekPet/ComfyUI_Custom_Nodes_AlekPet/assets/215304/08e38dff-3301-41f3-870b-51c74b74bfea)

**Comment by rezponze** [comment]
Sure! 

I'm on Firefox tho, but this is the console error: 

```
Create PainterNode: Paint_0 [painter_node.js:2750:17](http://127.0.0.1:8188/extensions/ComfyUI_Custom_Nodes_AlekPet/painter_node.js)
Uncaught (in promise) TypeError: LS_Painters[nodeNamePNG].settings.pipingSettings is undefined
    onNodeCreated http://127.0.0.1:8188/extensions/ComfyUI_Custom_Nodes_AlekPet/painter_node.js:2778
    onNodeCreated http://127.0.0.1:8188/extensions/core/saveImageExtraOutput.js:25
    onNodeCreated http://127.0.0.1:8188/extensions/core/widgetInputs.js:371
    createNode http://127.0.0.1:8188/lib/litegraph.core.js:478
    createNode http://127.0.0.1:8188/extensions/cg-use-everywhere/use_everywhere.js:260
    select http://127.0.0.1:8188/lib/litegraph.core.js:11671
    addResult http://127.0.0.1:8188/lib/litegraph.core.js:11985
[painter_node.js:2778:1](http://127.0.0.1:8188/extensions/ComfyUI_Custom_Nodes_AlekPet/painter_node.js)
Source map error: request failed with status 404
Resource URL: http://127.0.0.1:8188/extensions/ComfyUI_Custom_Nodes_AlekPet/lib/posenode/fabric.js
Source Map URL: /sm/4595deba885e6b95e012cf1ed9deed8a7b30edf3ae4c7d4bd5cc11d619b75c11.map
```

And then there's a link to learn more about the error that points here: https://developer.mozilla.org/en-US/docs/Web/JavaScript/Reference/Errors/Unexpected_type?utm_source=mozilla&utm_medium=firefox-console-errors&utm_campaign=default

Hope it helps!

**Comment by AlekPet** [comment]
The thing is that there is no pipingSettings value in localStorage.  You just need to clear localStorage so that it re-creates the missing properties.  You can type in the console
```js
localStorage.setItem("ComfyUI_Painter", JSON.stringify({}));
```
 and reload the page.

**Comment by rezponze** [comment]
Worked! Thanks! Closing the issue
