### ISSUE TITLE
failed

### ISSUE THREAD

**Issue by valleyss** [AlekPet/ComfyUI_Custom_Nodes_AlekPet#56]
Starting server

To see the GUI go to: http://0.0.0.0:8188
[INFO] No pre-start script found. Skipping.
########################################
[INFO] Starting ComfyUI...
########################################
## ComfyUI-Manager: installing dependencies done.
** ComfyUI startup time: 2024-06-01 16:58:40.883176
** Platform: Linux
** Python version: 3.11.9 (main, Apr 08 2024, 06:18:15) [GCC]
** Python executable: /usr/bin/python3
** Log path: /home/runner/comfyui.log

Prestartup times for custom nodes:
   2.7 seconds: /home/runner/ComfyUI/custom_nodes/ComfyUI-Manager

Total VRAM 8099 MB, total RAM 7880 MB
pytorch version: 2.3.0+cu121
xformers version: 0.0.26.post1
Forcing FP16.
Set vram state to: NORMAL_VRAM
Device: cuda:0 NVIDIA GeForce GTX 1070 : cudaMallocAsync
VAE dtype: torch.float32
Using xformers cross attention
### Loading: ComfyUI-Impact-Pack (V5.8.1)
[ComfyUI-Manager] default cache updated: https://raw.githubusercontent.com/ltdrdata/ComfyUI-Manager/main/model-list.json
[ComfyUI-Manager] default cache updated: https://raw.githubusercontent.com/ltdrdata/ComfyUI-Manager/main/alter-list.json
[ComfyUI-Manager] default cache updated: https://raw.githubusercontent.com/ltdrdata/ComfyUI-Manager/main/github-stats.json
[ComfyUI-Manager] default cache updated: https://raw.githubusercontent.com/ltdrdata/ComfyUI-Manager/main/extension-node-map.json
[ComfyUI-Manager] default cache updated: https://raw.githubusercontent.com/ltdrdata/ComfyUI-Manager/main/custom-node-list.json
### Loading: ComfyUI-Impact-Pack (Subpack: V0.5)
[Impact Pack] Wildcards loading done.
------------------------------------------
Comfyroll Studio v1.76 :  175 Nodes Loaded
------------------------------------------
** For changes, please see patch notes at https://github.com/Suzie1/ComfyUI_Comfyroll_CustomNodes/blob/main/Patch_Notes.md
** For help, please see the wiki at https://github.com/Suzie1/ComfyUI_Comfyroll_CustomNodes/wiki
------------------------------------------
Workspace manager - Openning file hash dict
### Loading: Workspace Manager (V1.0.0)
[Crystools INFO] Crystools version: 1.12.0
[Crystools INFO] CPU: Intel(R) Core(TM) i3-4150 CPU @ 3.50GHz - Arch: x86_64 - OS: Linux 6.8.0-31-generic
[Crystools INFO] GPU/s:
[Crystools INFO] 0) NVIDIA GeForce GTX 1070
[Crystools INFO] NVIDIA Driver: 550.54.15
A new version of Albumentations is available: 1.4.8 (you have 1.4.7). Upgrade using: pip install --upgrade albumentations
### [START] ComfyUI AlekPet Nodes ###
Node -> ArgosTranslateNode [Loading]
Node -> DeepTranslatorNode [Loading]
Node -> ExtrasNode [Loading]
Node -> GoogleTranslateNode [Loading]
Node -> PainterNode [Loading]
Node -> PoseNode [Loading]
### [END] ComfyUI AlekPet Nodes ###
Traceback (most recent call last):
  File "/home/runner/ComfyUI/nodes.py", line 1879, in load_custom_node
    module_spec.loader.exec_module(module)
  File "<frozen importlib._bootstrap_external>", line 940, in exec_module
  File "<frozen importlib._bootstrap>", line 241, in _call_with_frames_removed
  File "/home/runner/ComfyUI/custom_nodes/ComfyUI_Custom_Nodes_AlekPet/__init__.py", line 164, in <module>
    from .DeepTranslatorNode.deep_translator_node import DeepTranslatorCLIPTextEncodeNode, DeepTranslatorTextNode
  File "/home/runner/ComfyUI/custom_nodes/ComfyUI_Custom_Nodes_AlekPet/DeepTranslatorNode/deep_translator_node.py", line 7, in <module>
    import deep_translator
ModuleNotFoundError: No module named 'deep_translator'

Cannot import /home/runner/ComfyUI/custom_nodes/ComfyUI_Custom_Nodes_AlekPet module for custom nodes: No module named 'deep_translator'

Import times for custom nodes:
   0.0 seconds: /home/runner/ComfyUI/custom_nodes/websocket_image_save.py
   0.0 seconds: /home/runner/ComfyUI/custom_nodes/AIGODLIKE-ComfyUI-Translation
   0.0 seconds: /home/runner/ComfyUI/custom_nodes/ComfyUI_IPAdapter_plus
   0.2 seconds: /home/runner/ComfyUI/custom_nodes/OneButtonPrompt
   0.2 seconds: /home/runner/ComfyUI/custom_nodes/images-grid-comfy-plugin
   0.3 seconds: /home/runner/ComfyUI/custom_nodes/ComfyUI-Manager
   0.3 seconds: /home/runner/ComfyUI/custom_nodes/ComfyUI-Custom-Scripts
   0.4 seconds: /home/runner/ComfyUI/custom_nodes/comfyui-workspace-manager
   0.5 seconds: /home/runner/ComfyUI/custom_nodes/Derfuu_ComfyUI_ModdedNodes
   0.6 seconds: /home/runner/ComfyUI/custom_nodes/ComfyUI-NegiTools
   1.0 seconds: /home/runner/ComfyUI/custom_nodes/ComfyUI_Comfyroll_CustomNodes
   1.1 seconds: /home/runner/ComfyUI/custom_nodes/ComfyUI_kkTranslator_nodes
   4.1 seconds: /home/runner/ComfyUI/custom_nodes/ComfyUI-Crystools
   7.8 seconds: /home/runner/ComfyUI/custom_nodes/ComfyUI-Impact-Pack
  10.1 seconds: /home/runner/ComfyUI/custom_nodes/ComfyUI_InstantID
  33.7 seconds (IMPORT FAILED): /home/runner/ComfyUI/custom_nodes/ComfyUI_Custom_Nodes_AlekPet

Starting server

To see the GUI go to: http://0.0.0.0:8188

**Comment by AlekPet** [comment]
Hello, you do not have the deep-translator module installed, you need to install it, you can do it through comfyui manager or manually, through the terminal.

You need to go to Manager → Install PIP packages → put deep-translator and restart.

**Comment by valleyss** [comment]
Thank you very much, I solved this problem. I am using docker. The python environment required by the node is missing and cannot be installed automatically. After manually installing the environment and modifying some codes, it works fine.
