### ISSUE TITLE
Painter node does now show the canvas part

### ISSUE THREAD

**Issue by FemBoxbrawl** [AlekPet/ComfyUI_Custom_Nodes_AlekPet#58]
The pose node does work, but not the painter node

On Chrome,
Console:

app.js:1431 Error loading extension /extensions/ComfyUI_Custom_Nodes_AlekPet/painter_node.js 
TypeError: Failed to fetch dynamically imported module: http://localhost:7801/ComfyBackendDirect/extensions/ComfyUI_Custom_Nodes_AlekPet/painter_node.js

painter node.js is in the folder,

 so is fabric.js

----

I typed in this into the console: localStorage.setItem("ComfyUI_Painter", JSON.stringify({}));

it gave back "undefined"

no idea what to do. I am using stable swarm UI but it should not be any different from comfyUI really i think

**Comment by FemBoxbrawl** [comment]
okay this seems to be an issue with stable swarm UI since it works on regular comfyUI just fine

**Comment by chenFe-1** [comment]
I encountered the same problem as you, have you solved it?
