### ISSUE TITLE
I installed this pugins and it cause a big bug that I can't open ComfyUI

### ISSUE THREAD

**Issue by Qiuliuyang** [AlekPet/ComfyUI_Custom_Nodes_AlekPet#6]
strict-origin-when-cross-origin

**Comment by AlekPet** [comment]
Hello. Try taking out each folder one by one from the custom_nodes/ComfyUI_Nodes_AlekPet folder, where my nodes are located, to understand which node is causing this error. Start from the TranslateNode folder and restart ComfyUI. Tell us which node is issuing this message.

**Comment by Qiuliuyang** [comment]
> Hello. Try taking out each folder one by one from the custom_nodes/ComfyUI_Nodes_AlekPet folder, where my nodes are located, to understand which nodes is causing this error. Start from the TranslateNode folder and restart ComfyUI. Tell me which node is issuing this message.

Oh tanks，the problem just solved，I waited ten more minutes and I can open the server，I
 think maybe it just take a while to install

**Comment by AlekPet** [comment]
Wonderful!
