### ISSUE TITLE
Please fix the painter node to work on Stable Swarm UI.

### ISSUE THREAD

**Issue by FemBoxbrawl** [AlekPet/ComfyUI_Custom_Nodes_AlekPet#60]
I tried it with regular comfyUI, it worked perfectly, but in swarm it gives a blank gray panel. nothing.

would be nice to fix

**Comment by AlekPet** [comment]
Hi, ok, I'll see what's wrong there.

**Comment by FemBoxbrawl** [comment]
> Hi, ok, I'll see what's wrong there.

I figured it out i am quite sure, in the painter_node.js

I changed 
(line 8 and 9)
import { app } from "/scripts/app.js";
import { api } from "/scripts/api.js";

(line 8 and 9)
import { app } from "../../scripts/app.js";
import { api } from "../../scripts/api.js";

**Comment by AlekPet** [comment]
Updated the paths to the scripts for the finicky Stable Swarm UI :blush:
