### ISSUE TITLE
Has the API key expired?

### ISSUE THREAD

**Issue by starryCSDN** [AlekPet/ComfyUI_Custom_Nodes_AlekPet#61]
[Deep Translator] Service: "GoogleTranslator"
[Deep Translator] Authorization input field is empty!
Deep Translator] Service detect language disabled! Services support: DeeplTranslator, QcriTranslator, LingueeTranslator, PonsTranslator, PapagoTranslator, BaiduTranslator, MyMemoryTranslator.
The selected service has its own way of detecting the language.
Property "detect_lang_api_key" in Authorization data is empty or incorrect!

**Comment by AlekPet** [comment]
> [Deep Translator] Service: "GoogleTranslator" [Deep Translator] Authorization input field is empty! Deep Translator] Service detect language disabled! Services support: DeeplTranslator, QcriTranslator, LingueeTranslator, PonsTranslator, PapagoTranslator, BaiduTranslator, MyMemoryTranslator. The selected service has its own way of detecting the language. Property "detect_lang_api_key" in Authorization data is empty or incorrect!

No, it has not expired, this message says that you are using a service that itself determines the source language and is not using the detect_language service (https://detectlanguage.com/documentation), it is used for other services.

**Comment by starryCSDN** [comment]
Thank you, it seems that my proxy may not be working effectively, as I've been stuck at the translation node。
> > [Deep Translator] Service: "GoogleTranslator" [Deep Translator] Authorization input field is empty! Deep Translator] Service detect language disabled! Services support: DeeplTranslator, QcriTranslator, LingueeTranslator, PonsTranslator, PapagoTranslator, BaiduTranslator, MyMemoryTranslator. The selected service has its own way of detecting the language. Property "detect_lang_api_key" in Authorization data is empty or incorrect!
> 
> Hi. No, it has not expired, this message says that you are using a service that itself determines the source language and is not using the detect language service (https://detectlanguage.com/documentation), it is used for other services.
