### ISSUE TITLE
Why specify -s option when installing module requirements?

### ISSUE THREAD

**Issue by Maslino** [AlekPet/ComfyUI_Custom_Nodes_AlekPet#65]
This line:

https://github.com/AlekPet/ComfyUI_Custom_Nodes_AlekPet/blob/f2a3f4d7d6df5df6f60afac12c6db20724e0fb44/__init__.py#L75

According to `python3 -h`:

```
-s     : don't add user site directory to sys.path; also PYTHONNOUSERSITE
```

If ComfyUI's and other custom nodes' requirements were all installed to user site directory, -s option would cause some packages including cuda and torch to be re-installed in system site directory. That won't be good.

**Comment by AlekPet** [comment]
Hello.This flag is needed to avoid conflicts with already installed packages, the versions of which may not be compatible.

**Comment by Maslino** [comment]
I don't think so. If there are some incompatible packages, you can specify the right versions that won't confilict.

In my situation, I install ComfUI and some custom nodes' requirements all to user site directory. But when I install ComfyUI_Custom_Nodes_AlekPet, it stucks at installing requirements such as cuda, torch related packages. The torch package and maybe some other packages are big ones that would take long time to download, so it appears to stuck. These packages had already installed into user site directory, why re-install again?

By the way, ComfyUI-Manager install custom nodes' requirements without using -s option.

https://github.com/ltdrdata/ComfyUI-Manager/blob/29899a6177931cacb17f6f1ed07429786fbb2fda/glob/manager_core.py#L409

**Comment by AlekPet** [comment]
Hello, this is most likely due to the ArgosTranslate node, for some reason it reinstalls the packages again, even the absence of the -s flag may not help.  I'll update my code and remove the -s flag.  Thank you ;)!
