### ISSUE TITLE
can't load to translate list

### ISSUE THREAD

**Issue by tiandaoyuxi** [AlekPet/ComfyUI_Custom_Nodes_AlekPet#67]
![image](https://github.com/user-attachments/assets/3398d9f4-c831-4720-87d0-0022427e83fd)
only english

**Comment by AlekPet** [comment]
> ![image](https://github.com/user-attachments/assets/3398d9f4-c831-4720-87d0-0022427e83fd)
> only english

Hello, everything is correct, if you look at the list, there is a translation from Russian only into English. See here https://www.argosopentech.com/argospm/index/ or https://argos-translate.readthedocs.io/en/latest/source/gui.html#installing-a-language

**Comment by tiandaoyuxi** [comment]
![image](https://github.com/user-attachments/assets/e061b5f1-4b70-4d5f-a56c-931852d553b6)
I was planning to use it for two-way translation, and I modified some of the code and it's done. Thank you very much!
![image](https://github.com/user-attachments/assets/d7b0d703-763e-4d31-b587-5d91a0efdfd9)
