### ISSUE TITLE
pose node show red

### ISSUE THREAD

**Issue by Abhijeetisilanos** [AlekPet/ComfyUI_Custom_Nodes_AlekPet#69]

**Comment by AlekPet** [comment]
Check version my nodes last v1.0.13
Check file \ComfyUI_portables\ComfyUI\custom_nodes\ComfyUI_Custom_Nodes_AlekPet\PoseNode\js\pose_node.js

Check line 10, it must be `import { $el } from "../../scripts/ui.js";` but not import { $el } from "../../../scripts/ui.js"; 

The latest version fixes this. https://github.com/AlekPet/ComfyUI_Custom_Nodes_AlekPet/commit/17d23aca855ec2ee851c4ecc7244df64dac5bdd4
