### ISSUE TITLE
May I ask whether these three button ICONS can be set to hide and start? Sometimes I accidentally hit the horn icon. Thank you

### ISSUE THREAD

**Issue by shumoLR** [AlekPet/ComfyUI_Custom_Nodes_AlekPet#74]
![image](https://github.com/user-attachments/assets/9b54c8e6-d6eb-4845-b09b-89cf1379dfb5)

**Comment by AlekPet** [comment]
Hello. https://github.com/AlekPet/ComfyUI_Custom_Nodes_AlekPet/tree/master/ExtrasNode#additional-extensions

**Comment by shumoLR** [comment]
> Hello. https://github.com/AlekPet/ComfyUI_Custom_Nodes_AlekPet/tree/master/ExtrasNode#additional-extensions

Thank you
