### ISSUE TITLE
Speech recognition floating icons

### ISSUE THREAD

**Issue by kakachiex2** [AlekPet/ComfyUI_Custom_Nodes_AlekPet#78]
Your speech recognition icons wen minimizes the CLIPTextEncodeFlux start floating around.
![Screenshot 2024-08-24 000226](https://github.com/user-attachments/assets/172e6b13-cca2-4ef7-95bb-7308d451d67c)

**Comment by AlekPet** [comment]
> Your speech recognition icons wen minimizes the CLIPTextEncodeFlux start floating around.
> ![Screenshot 2024-08-24 000226](https://github.com/user-attachments/assets/172e6b13-cca2-4ef7-95bb-7308d451d67c)
> 

Hi, disable them in the options, I'll see when I have time.

**Comment by AlekPet** [comment]
Fixed!
