### ISSUE TITLE
 preview text

### ISSUE THREAD

**Issue by xianrenzhang0318** [AlekPet/ComfyUI_Custom_Nodes_AlekPet#8]
The preview text is invalid.no effect

**Comment by AlekPet** [comment]
I checked it, it works. What kind of node are you connecting?
![PREVIEW_TEXT](https://i.ibb.co/55m5BBD/preview.jpg "PREVIEW_TEXT")

**Comment by xianrenzhang0318** [comment]
Thank you for replying to me. I used translation + preview text, and it can be used now. I don’t know if it is related to the network. However, the preview text of other nodes does not have this problem, and this has also been invalid before, even It needs to be refreshed before it can be deleted. I don’t know if its instability is related to other nodes.
