### ISSUE TITLE
"Cannot connect proxy"

### ISSUE THREAD

**Issue by Mikezheng66** [AlekPet/ComfyUI_Custom_Nodes_AlekPet#82]
![20240905-171655](https://github.com/user-attachments/assets/05188714-1a8b-44b2-9eb9-68ead52765ac)

can not connect, "Cannot connect proxy" is displayed.

**Comment by AlekPet** [comment]
![deeeaaa](https://github.com/user-attachments/assets/2cb435bf-65b3-4536-b0f4-5f21f7c188e2)
Hello. I checked and changed the regular expression for checking the proxy and added proxy information to the console, update. And specify https at the beginning of the proxy, because http may not work. 😄
